apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: voting-app
  template:
    metadata:
      name: postgres
      labels:
        name: postgres-pod
        app: voting-app

    spec:
      containers:
        - name: postgres
          image: postgres:9.5
          env:
            - name: POSTGRES_PASSWORD
              value: "password"
          ports:
            - containerPort: 5432