apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: voting-app
  template:
    metadata:
      name: redis
      labels:
        name: redis-pod
        app: voting-app

    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379